### ISSUE TITLE
Dynlibs 

### ISSUE THREAD

**Issue by vgartner** [reyjieroque/delphi-clamav#3]
Error trying to compile with Delphi XE7:
[dcc32 Fatal Error] clamav3.pas(415): F1026 File not found: 'Dynlibs.dcu'
This is a Free Pascal file, right? How to proceed to compile under Delphi?

**Comment by reyjieroque** [comment]
You can try the latest commit for clamav3.pas - you just need to add some conditional define like "WINDOWS".. Also a scan option in clamav3 (CL_SCAN_STDOPT) if you receive an error.
